### ISSUE TITLE
Trips show up in tables, but cannot be accessed directly

### ISSUE THREAD

**Issue by essoen** [capraconsulting/dih-webapp#262]
The data for trip 777 cannot be accessed:
https://app.drapenihavet.no/admin/trips/777 

Possibly related to #263 and may have to do with the [API](https://github.com/capraconsulting/dih-api)

**Comment by scbasma** [comment]
See [PR](https://github.com/capraconsulting/dih-api/pull/140).

**Comment by larseen** [comment]
This has been fixed in https://github.com/capraconsulting/dih-api/pull/140 closing this.
