### ISSUE TITLE
User associated with a trip cannot be found

### ISSUE THREAD

**Issue by essoen** [capraconsulting/dih-webapp#263]
It seems that some users associated with a trip has disappeared, i.e. trip with id 777:
https://app.drapenihavet.no/admin/trips/777 

The user Isabel Retuerto Millán that is associated with trip 777 cannot be found when searching under users.

Report from DIH:
> Isabel Retuerto Millan og Elisha Nader (elishanader@gmail.com) (Elisha får jeg ikke opp i søkefeltet inne i destinasjonen Chios, hun finner jeg kun om jeg går via 'Users'. Isabel sin profil er utilgjengelig for meg da jeg kommer inn i andre brukere sin profil om jeg trykker på Isabel) 
> Jeg ser også at den registrerte reisen til Elisha plutselig er skiftet fra present til closed, til tross for at hun skal være på Chios frem til April. 

Possibly related to #262 and may have to do with the [API](https://github.com/capraconsulting/dih-api)

**Comment by essoen** [comment]
The user had been deleted.

@scbasma has to make user deletion include deletion of all related trips.

**Comment by scbasma** [comment]
See [PR](https://github.com/capraconsulting/dih-api/pull/140).

**Comment by larseen** [comment]
This has been fixed in https://github.com/capraconsulting/dih-api/pull/140 closing this.
